### ISSUE TITLE
Weird DNS/53 request

### ISSUE THREAD

**Issue by garncarz** [garncarz/dns-server#10]
```
dns_1     | Unhandled Error
dns_1     | Traceback (most recent call last):
dns_1     |   File "/usr/local/lib/python2.7/site-packages/twisted/names/dns.py", line 3061, in datagramReceived
dns_1     |     self.controller.messageReceived(m, self, addr)
dns_1     |   File "/usr/local/lib/python2.7/site-packages/twisted/names/server.py", line 554, in messageReceived
dns_1     |     self.handleQuery(message, proto, address)
dns_1     |   File "/usr/local/lib/python2.7/site-packages/twisted/names/server.py", line 381, in handleQuery
dns_1     |     return self.resolver.query(query).addCallback(
dns_1     |   File "/usr/local/lib/python2.7/site-packages/twisted/names/common.py", line 78, in query
dns_1     |     return defer.maybeDeferred(method, query.name.name, timeout)
dns_1     | --- <exception caught here> ---
dns_1     |   File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
dns_1     |     result = f(*args, **kw)
dns_1     |   File "/usr/local/lib/python2.7/site-packages/twisted/names/resolve.py", line 94, in lookupAllRecords
dns_1     |     d = self.resolvers[0].lookupAllRecords(name, timeout)
dns_1     | exceptions.AttributeError: 'Resolver' object has no attribute 'lookupAllRecords'
dns_1     |
```

Normal `dig <subdomain>.dyndns.mydomain.org` works alright, so maybe it's some uninvited usage? Better add some custom logging to handling of DNS requests.

**Comment by garncarz** [comment]
Also, this somehow missed Sentry.
